export const properties = [
  {
    id: "64392e46dfd90fb29e464fbf",
    title: "Summerhill Estate",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 2000,
    address: "Street 2",
    city: "Denver",
    country: "US",
    image: "https://i.pinimg.com/originals/89/56/5c/89565c305737e1da2a1a5b62600fbcd4.jpg",
    facilities: {
      bathrooms: "2",
      parking: "1",
      bedrooms: "2",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:43:18.186Z",
    updatedAt: "2023-04-14T10:43:18.186Z",
  },
  {
    id: "64392e32dfd90fb29e464fbe",
    title: "Riverstone Manor",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 2000,
    address: "Street 2",
    city: "Tampa",
    country: "US",
    image: "https://st.hzcdn.com/simgs/pictures/exteriors/builders-in-kochi-creo-homes-pvt-ltd-img~a751d25e0d2ef808_4-0254-1-cb5c87b.jpg",
    facilities: {
      bathrooms: "5",
      parking: "1",
      bedrooms: "4",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:42:58.826Z",
    updatedAt: "2023-04-14T10:42:58.826Z",
  },
  {
    id: "64392e1edfd90fb29e464fbd",
    title: "Autumn Mist Cottage",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 3800,
    address: "Street 2",
    city: "Karachi",
    country: "Pakistan",
    image: "https://e0.pxfuel.com/wallpapers/12/377/desktop-wallpaper-beautiful-houses-beautiful-mansion.jpg",
    facilities: {
      bathrooms: "2",
      parking: "1",
      bedrooms: "3",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:42:37.946Z",
    updatedAt: "2023-04-14T10:42:37.946Z",
  },
  {
    id: "64392e0bdfd90fb29e464fbc",
    title: "Coastal Breeze Villa",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 8000,
    address: "Street 2",
    city: "Multan",
    country: "Pakistan",
    image: "https://3.bp.blogspot.com/-84l-BoUL090/VTDHcQzSTNI/AAAAAAAAuHI/Khftta_CF5E/s1920/wow-home-design.jpg",
    facilities: {
      bathrooms: "5",
      parking: "1",
      bedrooms: "4",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:42:19.231Z",
    updatedAt: "2023-04-14T10:42:19.231Z",
  },
  {
    id: "64392df2dfd90fb29e464fbb",
    title: "Rolling Hills Retreat",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 2000,
    address: "Street 2",
    city: "Phoenix",
    country: "US",
    image: "https://www.hollywoodreporter.com/wp-content/uploads/2023/03/image_h_01-H-2023.jpg",
    facilities: {
      bathrooms: "7",
      parking: "2",
      bedrooms: "10",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:41:54.156Z",
    updatedAt: "2023-04-14T10:41:54.156Z",
  },
  {
    id: "64392dd8dfd90fb29e464fba",
    title: "Sapphire Shoreline",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 3000,
    address: "Street 2",
    city: "Karachi",
    country: "Pakistan",
    image: "https://img.zumpercdn.com/638605812/1280x960.jpg",
    facilities: {
      bathrooms: "1",
      parking: "1",
      bedrooms: "1",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:41:28.121Z",
    updatedAt: "2023-04-14T10:41:28.121Z",
  },
  {
    id: "64392dc3dfd90fb29e464fb9",
    title: "Golden Sun Mansion",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 6000,
    address: "Street 2",
    city: "Multan",
    country: "Pakistan",
    image: "https://cdn.onekindesign.com/wp-content/uploads/2016/09/Modern-Luxury-House-Feldman-Architecture-01-1-Kindesign.jpg",
    facilities: {
      bathrooms: "2",
      parking: "1",
      bedrooms: "2",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:41:07.576Z",
    updatedAt: "2023-04-14T10:41:07.576Z",
  },
  {
    id: "64392daddfd90fb29e464fb8",
    title: "Emerald Heights Estate",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 2400,
    address: "Street 2",
    city: "Denver",
    country: "US",
    image: "https://i.pinimg.com/originals/41/34/0e/41340e40b71b2adccacc93bce85035b6.jpg",
    facilities: {
      bathrooms: "4",
      parking: "2",
      bedrooms: "3",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:40:48.026Z",
    updatedAt: "2023-04-14T10:40:48.026Z",
  },
  {
    id: "64392d97dfd90fb29e464fb7",
    title: "Silver Meadow Cottage",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 1000,
    address: "Street 2",
    city: "Phoenix",
    country: "US",
    image: "https://cdn.architecturaldigest.com/wp-content/uploads/2021/10/AD1121_WELL_MH_33.jpg",
    facilities: {
      bathrooms: "3",
      parking: "1",
      bedrooms: "4",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:40:23.152Z",
    updatedAt: "2023-04-14T10:40:23.152Z",
  },
  {
    id: "64392d83dfd90fb29e464fb6",
    title: "Crystal Lake Villa",
    description: "Massive opportunity to build your dream home at the base of Mummy Mountain in the 3 C's school district. Home is currently updated and very livable if your plans are to build at a later date.* Bonus * to live hillside without hillside restrictions in the town of PV. Run don't walk to capture this needle in a hay stack.",
    price: 1500,
    address: "Street 2",
    city: "Tampa",
    country: "US",
    image: "https://www.architecturaldigest.com/house-of-pictorial-imagery.jpg",
    facilities: {
      bathrooms: "2",
      parking: "2",
      bedrooms: "3",
    },
    userEmail: "mukhtarhamza294@gmail.com",
    createdAt: "2023-04-14T10:40:03.456Z",
    updatedAt: "2023-04-14T10:40:03.456Z",
  },
];
